### ISSUE TITLE
problem with maven-site-plugin 3.7 and asciidoc 1.5.6.

### ISSUE THREAD

**Issue by ymmark0** [asciidoctor/asciidoctor-maven-plugin#327] opened 2018-01-03 20:00 UTC
I'm struggling to get maven-site-plugin 3.7 working together asciidoc 1.5.6, I keep getting errors in jruby.
With jruby version 9.1.14.0 or older, I get:
 
```
 Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.7:site (default-cli) on project collab: Execution default-cli of goal org.apache.maven.plugins:maven-site-plugin:3.7:site failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.7:site (default-cli) on project collab: Execution default-cli of goal org.apache.maven.plugins:maven-site-plugin:3.7:site failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.apache.maven.plugins:maven-site-plugin:3.7:site failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.lang.NullPointerException
        at org.jruby.RubyDir.getCWD(RubyDir.java:180)
        at org.jruby.RubyDir.getwd(RubyDir.java:421)
        at org.jruby.RubyDir$INVOKER$s$0$0$getwd.call(RubyDir$INVOKER$s$0$0$getwd.gen)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:298)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:127)
etc
 at org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:91)
        at org.jruby.gen.InterfaceImpl244426999.convert(org/jruby/gen/InterfaceImpl244426999.gen:13)
        at org.asciidoctor.internal.JRubyAsciidoctor.render(JRubyAsciidoctor.java:313)
        at org.asciidoctor.internal.JRubyAsciidoctor.render(JRubyAsciidoctor.java:448)
        at org.asciidoctor.internal.JRubyAsciidoctor.convert(JRubyAsciidoctor.java:531)
        at org.asciidoctor.maven.site.AsciidoctorParser.convertAsciiDoc(AsciidoctorParser.java:176)
        at org.asciidoctor.maven.site.AsciidoctorParser.parse(AsciidoctorParser.java:82)
        at org.apache.maven.doxia.DefaultDoxia.parse(DefaultDoxia.java:65)
        at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderDocument(DefaultSiteRenderer.java:461)
        at org.apache.maven.doxia.siterenderer.DoxiaDocumentRenderer.renderDocument(DoxiaDocumentRenderer.java:52)
        at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:349)
```

With jruby version 9.1.15.0 I get;
```
 Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.7:site (default-cli) on project collab: Execution default-cli of goal org.apache.maven.plugins:maven-site-plugin:3.7:site failed: org.jruby.exceptions.RaiseException: (RuntimeError) asciidoctor: FAILED: <stdin>: Failed to load AsciiDoc document - can't modify frozen Hash -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.7:site (default-cli) on project collab: Execution default-cli of goal org.apache.maven.plugins:maven-site-plugin:3.7:site failed: org.jruby.exceptions.RaiseException: (RuntimeError) asciidoctor: FAILED: <stdin>: Failed to load AsciiDoc document - can't modify frozen Hash
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.apache.maven.plugins:maven-site-plugin:3.7:site failed: org.jruby.exceptions.RaiseException: (RuntimeError) asciidoctor: FAILED: <stdin>: Failed to load AsciiDoc document - can't modify frozen Hash
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: org.asciidoctor.internal.AsciidoctorCoreException: org.jruby.exceptions.RaiseException: (RuntimeError) asciidoctor: FAILED: <stdin>: Failed to load AsciiDoc document - can't modify frozen Hash
        at org.asciidoctor.internal.JRubyAsciidoctor.render(JRubyAsciidoctor.java:317)
        at org.asciidoctor.internal.JRubyAsciidoctor.render(JRubyAsciidoctor.java:448)
        at org.asciidoctor.internal.JRubyAsciidoctor.convert(JRubyAsciidoctor.java:531)
```

I've tried a wide variety of maven-site-plugin and asciidoc version combinations, but so far none has worked.  

My pom for the plugin is currently as follows:
```
<plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-site-plugin</artifactId>
                    <version>3.7</version>
                    <configuration>
                        <!-- disable generateReports if you don't want to include the built-in reports -->
                        <generateReports>true</generateReports>
                        <generateSitemap>true</generateSitemap>
                        <relativizeDecorationLinks>false</relativizeDecorationLinks>
                        <locales>en</locales>
                        <inputEncoding>UTF-8</inputEncoding>
                        <outputEncoding>UTF-8</outputEncoding>
                        <asciidoc>
                            <baseDir>
                                <dir>target/doc/asciidoc</dir>
                            </baseDir>
                            <attributes>
                                <source-highlighter>coderay</source-highlighter>
                                <coderay-css>style</coderay-css>
                            </attributes>
                        </asciidoc>
                        <moduleExcludes>
                            <asciidoc>**/_*.adoc</asciidoc>
                        </moduleExcludes>
                    </configuration>
                    <dependencies>
                        <dependency><!-- add Asciidoctor Doxia Parser Module -->
                            <groupId>org.asciidoctor</groupId>
                            <artifactId>asciidoctor-maven-plugin</artifactId>
                            <version>1.5.6</version>
                        </dependency>
                        <dependency>
                            <groupId>org.jruby</groupId>
                            <artifactId>jruby-complete</artifactId>
                            <version>9.1.15.0</version>
                        </dependency>
                        <dependency>
                            <groupId>org.asciidoctor</groupId>
                            <artifactId>asciidoctorj</artifactId>
                            <version>1.5.6</version>
                        </dependency>
                    </dependencies>
                    <executions>
                        <execution>
                            <id>attach-descriptor</id>
                            <goals>
                                <goal>attach-descriptor</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
```
If there's more I can do to help diagnose, please let me know?
Thanks

**Comment by abelsromero** [comment] 2018-01-03 22:52
I can reproduce the issue when I add `<baseDir>`, without it, it works fine with all versions.
What are you trying to achieve with that?

**Comment by ymmark0** [comment] 2018-01-03 23:35
I was experimenting with changing the basedir because I have other plugins generating adoc that I want included in the site documentation.  I'll see if I can work around it.  Thanks for spotting that.

**Comment by ymmark0** [comment] 2018-01-04 08:56
Note I took baseDir from the asciidoc site documentation here:
https://github.com/asciidoctor/asciidoctor-maven-plugin#setup-1
Specifically it says:
> The Asciidoctor base directory (i.e., document root) is configured as src/site/asciidoc by default, though this can be overridden using the baseDir configuration option.

**Comment by abelsromero** [comment] 2018-01-04 10:24
Some things...
1. Note that `baseDir` is a string param. The Ruby exception appears because the parser ignores the `<dir>` and sets a null value which internally fails. We DO need to address, it is clearly a bug for me.
2. baseDir works, but is passed as-is and works differently from baseDir from the default goal. It must be and absolute path and Maven replacements (${project.basedir}) don't work. This imho make this quite impractical, instead you can use the standard site `siteDirectory` like `<siteDirectory>${project.build.directory}/doc</siteDirectory>`. With the cabeat that it adds `asciidoc` and you need to put the site.xml there too. I'll look into implementing a baseDir with the same functionality as the main goal.

**Comment by ymmark0** [comment] 2018-01-04 10:57
Great - thanks will give that a go.

**Comment by abelsromero** [comment] 2018-01-16 06:48
This has been fixed with https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/331

**Closed by abelsromero** 2018-01-16 06:48 UTC
Labels: bug, enhancement
