### ISSUE TITLE
PlantUML graphviz_dot smetana not working

### ISSUE THREAD

**Issue by mminke** [asciidoctor/asciidoctor-maven-plugin#522] opened 2021-03-25 19:17 UTC
- [ ] Bug report
- [ ] Feature request
- [x] Question

Hi,

We are using asciidoc in our projects for quite a while now and recently we started using Plantuml to create some diagrams. Because of the way our build environment is setup, the 'dot' executable is not available on our build servers. Therefor I want to use the 'internal' java dot implementation. But now I have the following issue:

To get the diagram properly created using the asciidoctor-maven-plugin I use the following in the document:

```
[plantuml, migration-context, svg]
....
!pragma graphviz_dot jdot
```

This properly creates the diagram in the end result.
However, in IntelliJ the asciidoc complains that jdot is renamed to smetana and will not display the diagram. So I change the document into:
```
[plantuml, migration-context, svg]
....
!pragma graphviz_dot smetana
```
Now it is correctly displayed in IntelliJ, but now the asciidoctor-maven-plugin does not correctly generate the diagram.
Looking at the documentation I think the IntelliJ plugin is more accurate as in all the docs I now find, smetana is mentioned and not jdot.

Now my question is, am I doing something wrong or do some versions need to be updated (either on my side, or your side).

Thanks in advance!

* asciidoctor-maven-plugin version: 2.1.0
* asciidoctorj version: 2.4.3
* asciidoctorj-diagram: 2.1.0

**Comment by abelsromero** [comment] 2021-03-25 20:11
First of all, many thanks for bringing this topic, I was not aware if this effors to remove `dot` deppendency and this is great!

On the issue, in both maven and intellj I could only make it work with `smetana` which as you mention seems the correct answer. The onyl docs I found are https://plantuml.com/smetana02, but everything seems consistent.
Could it be there's something in your system or classpath that adds jdot, which in turn breaks the build?

I tried with this doc

```
[plantuml, migration-context1, svg]
....
Class01 <|-- Class02
Class03 *-- Class04
Class05 o-- Class06
Class07 .. Class08
Class09 -- Class10
....

[plantuml, migration-context2, svg]
....
!pragma graphviz_dot jdot
Class01 <|-- Class02
Class03 *-- Class04
Class05 o-- Class06
Class07 .. Class08
Class09 -- Class10
....

[plantuml, migration-context3, svg]
....
!pragma graphviz_dot smetana
Class01 <|-- Class02
Class03 *-- Class04
Class05 o-- Class06
Class07 .. Class08
Class09 -- Class10
....
```

And here are my results. As expected, first fails due to not having dot in path, seconds shows `jdot` should be renamed, and the last one works as expected.

**Intellj preview**

![image](https://user-images.githubusercontent.com/5781153/112536298-909d0400-8dad-11eb-9f11-7ca763488978.png)


**Maven build** Using same config with latests versions as in https://github.com/asciidoctor/asciidoctor-maven-examples/tree/master/asciidoctor-diagram-example

![image](https://user-images.githubusercontent.com/5781153/112536368-aca0a580-8dad-11eb-8956-3baafc9d6016.png)

**Comment by abelsromero** [comment] 2021-04-20 12:27
Hi, given I could not reproduce and the behauviour is consistent with the docs, I will be closing the issue in 5 days.

**Comment by mminke** [comment] 2021-04-21 08:49
So I finally got it fixed. I do not know how this exactly works, but I needed to add the following properties in our pom.xml:

`
`

**Comment by abelsromero** [comment] 2021-04-21 09:09
Glad to hear. I hope you understand from time to time we need to do some cleanup 😅

**Closed by abelsromero** 2021-04-21 09:09 UTC
