### ISSUE TITLE
Does not show line numbers in source blocks with nowrap option

### ISSUE THREAD

**Issue by Rajind** [asciidoctor/asciidoctor-maven-plugin#256] opened 2016-08-03 07:56 UTC
I am using asciidoctor-maven-plugin v1.5.3. When I use source block with nowrap option and linenums, line numbers does not appear. 

I am using code block as follows.
![selection_001](https://cloud.githubusercontent.com/assets/5234766/17358177/345ccc06-597e-11e6-8775-992c1719b002.png)

**Comment by mojavelinux** [comment] 2016-08-03 08:14
The linenums must be the third positional attribute. The syntax is:

```
[source, language, linenums]
```

If you mix up the order, then you have to set linenums as follows:

```
linenums=
```

I recommend writing it as:

```
[source%nowrap, linenums=]
```

Keep in mind that line numbers are only added if the source block has a language specified. The previous syntax assumes the language is set on the document using something like:

```
:source-language: java
```

**Comment by Rajind** [comment] 2016-08-03 08:54
@mojavelinux thank you for fast response. I've trying all of the following ways and i do get the line numbers but then **i do not get no wrapping**.

![selection_002](https://cloud.githubusercontent.com/assets/5234766/17359786/ce301bd8-5985-11e6-8b15-279d8bf5fa01.png)

**Comment by mojavelinux** [comment] 2016-08-03 19:53
This appears to be a duplicate of https://github.com/asciidoctor/asciidoctor/issues/1706 (which I now understand).

**Closed** 2021-02-01 03:43 UTC
