### ISSUE TITLE
Problems on Java 9

### ISSUE THREAD

**Issue by ecki** [asciidoctor/asciidoctor-maven-plugin#287] opened 2017-03-24 16:55 UTC
I might be a bit early, but just so that it is not forgotten. The AsciiDoctor Maven Plugin fails when executed inside maven with Java 9:

    [ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc
        (asciidoc-to-html) on project reference-manual: Execution asciidoc-to-html of goal 
        org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc failed: (LoadError) load error:
         jruby/java/java_ext/java.lang -- java.lang.reflect.InaccessibleObjectException: Unable to make 
        protected native java.lang.Object java.lang.Object.clone() throws java.lang.Clone
        NotSupportedException accessible: module java.base does not "opens java.lang" to unnamed module 

This might be directly related to this JRuby bug: https://github.com/jruby/jruby/issues/4111

    Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T18:37:52+01:00)
    Maven home: D:\devenv\apache-maven-3.2.1
    Java version: 9-ea, vendor: Oracle Corporation
    Java home: c:\Program Files\Java\jdk-9
    Default locale: de_DE, platform encoding: Cp1252
    OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"

    <jruby.version>1.7.25</jruby.version>

**Comment by abelsromero** [comment] 2017-03-24 17:06
Just curious, what happens when you try running the plugin with the last JRuby version (9.1.8.0)?

**Comment by ecki** [comment] 2017-03-24 17:29
@abelsromero  cool, that works, thank you. At least output-html5 now completes. the pdf backend fails (only on Java 9, on Java 8 it works with Jruby 9.1)

    [ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc
    (output-pdf) on project reference-manual: Execution out put-pdf of goal
    org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc failed: (LoadError) library `zlib' could not be loaded:
    java.lang.ExceptionInInitializerError -> [Help 1]
    org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal
    org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc (output-pdf) on project
    reference-manual: Execution output-pdf of goal
    org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc failed:
    (LoadError) library `zlib' could not be loaded: java.lang.ExceptionInInitializerError
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:547)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
    Caused by: org.apache.maven.plugin.PluginExecutionException: Execution output-pdf of goal 
        org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc failed:
        (LoadError) library `zlib' could not be loaded: java.lang.ExceptionInInitializerError
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:144)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
    Caused by: org.jruby.exceptions.RaiseException:
        (LoadError) library `zlib' could not be loaded: java.lang.ExceptionInInitializerError
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:961)
        at RUBY.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55)

**Comment by ecki** [comment] 2017-03-24 17:33
(I see there are some updates to the pdf-core Gem. I am not sure if I want to open that box. Would that be a bug against asciidoctorj-pdf (using 1.5.0-alpha.11) or more against the ruby part?)

**Comment by abelsromero** [comment] 2017-03-24 17:51
> I am not sure if I want to open that box

Until Java 9 is settled I would not push further. JRuby team is aware they need to keep an eye on compatibility and we can use this issue to keep track of it.

Regarding the pdf, I am not sure I follow, right now asciidoctorJ-pdf and asciidocotr-pdf are aligned, both at version alpha.14. AsciidoctorJ and asciidoctor-maven-plugin 1.5.5 were published last week.

Btw, thanks a lot for testing. I don't Java9 installed right now and that helps a lot.

**Comment by mojavelinux** [comment] 2017-03-25 01:23
> I see there are some updates to the pdf-core Gem. I am not sure if I want to open that box. 

It's very unlikely that a problem running on Java 9 would be solved by a change to the Ruby code. The main purpose of JRuby is to make sure that Ruby code runs on the JVM the same way it runs on MRI (C Ruby). If there are compatibility issues with Java 9, it either involved JRuby or something we're doing in AsciidoctorJ (either at runtime or how we package).

**Comment by Sanne** [comment] 2017-11-27 10:36
I'd love to see some progress on this; we're thinking to baseline our builds on Java 9 soon, only the documentation build is not compaible yet.

**Comment by mojavelinux** [comment] 2017-11-27 10:39
My understanding is that if you use the latest release of Java 9, it should work. We haven't tested it in CI yet, but it has been reported.

**Comment by Sanne** [comment] 2017-11-27 12:07
Hi @mojavelinux ! It kinda works but I either get several exceptions or we need to override the JVM settings, which prevents us to running tests in the stricter mode.

Interestingly when using the bleeding edge latest of each asciidoctor component I still have exceptions logged all over but it seems to produce the right output, at least when publishing as html.

For this to work out I have to do all of:
 1. use alpha (latest) of each asciidoctor component
 2. override pretty much all versions of each dependency of the `asciidoctor-maven-plugin` 
 3. allowing reflection on java.security.cert and java.util.zip (both in module java.base)

Happy to test any combination, I suspect we just need some guidance about what you'd expect to work and in which conditions? 

An alternative would be to have the asciidoctor-maven-plugin allow to start in a forked JVM so that we can override JVM settings for it, without having to taint all other components with flags we can't have?

**Comment by mojavelinux** [comment] 2017-11-28 09:00
Hey @Sanne!

What we've lacked thus far are Java 9 testers. If you're willing to poke at some combinations, that will really help move this forward.

Technically speaking, if JRuby works cleanly on Java 9, I would expect AsciidoctorJ to work cleanly on Java 9 too. But there could be things we're doing in AsciidoctorJ that are not Java 9 compatible. But that wouldn't be nearly as hard to fix.

There's an open issue to get the AsciidoctorJ CI job running on Java 9. That's really the first step. Once we can verify that works, only then can we really expect the Maven plugin to work. See https://github.com/asciidoctor/asciidoctorj/issues/591.

**Comment by PerfectSlayer** [comment] 2018-02-14 19:03
According the last update of asciidoctorj, it seems to work now.
Even if the issue is not closed, did you found any other blocking problem to update to Java 9?

**Comment by Sanne** [comment] 2018-02-14 19:12
I'd be super happy to try it out again tomorrow. Could someone please suggest me which versions of asciidoctorj, asciidoctor-maven-plugin, etc.. should be safe to combine?

**Comment by Diros1234** [comment] 2018-02-14 19:51
The asciidoctor-maven-examples were just recently updated & tested with Java9. You can check them to see what versions you need to set depending on your use case; site, pdf, html, etc. Or if you can point us to a specific repo we can have a look.
One caveat though is that if you use Java extensions you may need to use an Asciidoctorj snapshot a soon as this is merged: https://github.com/asciidoctor/asciidoctorj/pull/625.

**Comment by Sanne** [comment] 2018-02-14 23:14
ok, so I couldn't wait for tomorrow as I wanted to see it.. unfortunately there still are tons of errors.
Hopefully it's just me as it's very late here ;)

I checked the `asciidoctor-maven-examples` and made sure to align all our dependencies to use the same versions. I'm surprised to see they still use JRuby 1.7, which supposedly doesn't work properly on Java 9.

The html output seems to work, but the terminal spits out a very uncomfortable amount of exceptions in background so I'm not confident it's working fine, I would need to produce a detailed diff with previous builds.

The pdf output just fails with an error:

    [ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.6:process-asciidoc (output-pdf) on project hibernate-search-documentation: Execution output-pdf of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.6:process-asciidoc failed: (LoadError) library `zlib' could not be loaded: java.lang.ExceptionInInitializerError -> [Help 1]

If you'd like to have a look, our repository is public and easy to fork:
 - https://github.com/hibernate/hibernate-search

You won't need any setup at all, other than have  JDK9 installed to try it out.
To have it skip our tests, etc and get straight to build the documentation right away:

    mvn clean install -Pdocumentation-pdf -f documentation/pom.xml -Dcheckstyle.skip

We're not using any extensions in this project, hopefully that will simplify things.

Any suggestion appreciated.. thanks all!

**Comment by abelsromero** [comment] 2018-02-15 10:01
As you mentioned I could build the project on Windows7, MacOS & Ubuntu 16.04 with some error & warning messages. But as for my research they are normal and don't affect the build.

The versions that worked best are the last versions for all components:
```
        <asciidoctor-maven-plugin.version>1.5.6</asciidoctor-maven-plugin.version>
        <jruby.version>9.1.15.0</jruby.version>
        <asciidoctorj.version>1.5.6</asciidoctorj.version>
        <asciidoctorj-pdf.version>1.5.0-alpha.16</asciidoctorj-pdf.version>
```
_Regarding versions:_
jRuby 17.26 also worked, but the performance with 9.1.15.0 was better. Also, asciidoctorj-pdf alpha.16 takes longer than previous versions, the build in my (crappy) machine went from ~55sec to ~2 min time. With 1.7.26 it was 3 minutes.

_About the warning & error messages:_
There are 2. The firstc comes from Asciidoctor `asciidoctor: WARNING: mapping.asciidoc: line 1087: id assigned to section already in use: analyzer` and appears only during PDF generations. That's normal and is caused becasuse the automatic anchors that are created for all subsection titles. Each section has an id with a prefix (default: `_`), but in your PDF build you set the prefix as empty, creating a collision between the `=== Analyzer` and the marl `[[analyzer]]`. Just remove the `<idprefix/>` from the pom.

The other warnings are related to changes in the visibility of low-level Java API in Java9. It's a WIP of the JRuby team and the messages change depending on the OS https://github.com/jruby/jruby/issues/4834.
I could not reproduce the exact error you got, in my case all message show something like
````
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.runtime.encoding.EncodingService (file:/C:/Users/asalgadr/.m2/repository/org/jruby/jruby-complete/9.1.14.0/jruby-complete-9.1.14.0.jar) to field java.io.Console.cs
WARNING: Please consider reporting this to the maintainers of org.jruby.runtime.encoding.EncodingService
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
``
The especific class is what changes from OS to OS.
If it really bothers you you can add some flags to remove them.

Please, let us know if it worked in your machine.

**Comment by Sanne** [comment] 2018-02-15 15:23
Thanks so much for having a look @abelsromero, indeed you fixed the error we had with PDFs.

I'm well aware of what the Jigsaw related warnings mean and have also been testing with JRuby 9 in the past, but there (used to be?) many compatibility issues between JRuby 9 and asciidoctor so I wasn't too comfortable to just override the JRuby version and cross fingers without knowing more...

(The `asciidoctor-maven-examples` isn't using JRuby 9 either, maybe update that if you think it's good enough now?)

I'll start using these and let you know if I have more problems.

Thanks!

Related:
 - https://hibernate.atlassian.net/browse/HSEARCH-3011
 - https://github.com/hibernate/hibernate-search/pull/1631

**Comment by abelsromero** [comment] 2018-02-15 17:34
> you fixed the error we had with PDF

Haha, I did not fix anything I am just a janitor, you should thank others.

> I wasn't too comfortable to just override the JRuby version

Feel free to do, it's by design that we allow to change the version. We try to offer compatibility with older versions for max compatibilty. The default AsciidoctorJ and jRuby versions are just for convenience.
I'd recommed to use the latest JRuby always.

**Closed** 2018-02-16 15:18 UTC
