### ISSUE TITLE
how can i customize the google css and font-awesome.min.css

### ISSUE THREAD

**Issue by aximo** [asciidoctor/asciidoctor-maven-plugin#167] opened 2015-08-25 09:14 UTC
anybody know how to customize the google css and font-awesome.min.css when rendering html via maven plugins

I want to use the local css nor access it via internet.

**Comment by mojavelinux** [comment] 2015-08-25 10:05
You can use attributes to control this behavior. You can find out how these are controlled in the converter.

* https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/html5.rb#L55
* https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/html5.rb#L74

Try the following settings:

```
:webfonts!:
:iconfont-remote!:
```

If you disable webfonts, then you have to load your own in a custom stylesheet or using docinfo. There isn't a way to control the path directly yet. My suggestion is to use the `linkcss` attribute and copy the Asciidoctor stylesheet into your project.

(I recognize this needs to be better documented).

**Comment by aximo** [comment] 2015-08-25 10:17
you are right, thanks, i  also find another way in pom.xml:
```xml
                        <webfonts>false</webfonts>
								<iconfont-remote>false</iconfont-remote>
								<iconfont-name>font-awesome-4.1.0/css/font-awesome</iconfont-name>
								<!--
								<stylesheet>my-theme.css</stylesheet>
								-->
                            </attributes>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by mojavelinux** [comment] 2015-08-25 18:01
:+1:

**Comment by abelsromero** [comment] 2015-08-25 21:01
To close this issue I was adding a small note about `iconfont-*` attributes in the user manual, but I have a doubt.
This only works when set as attributes in the CLI and not when defined in the document attributes section. Is it by design?

These are the current changes in my repo https://github.com/abelsromero/asciidoctor.org/commit/6b73e3b587350f9c0a18cef6b9b4c2cfc9493092

It's just a really small thing.

**Comment by mojavelinux** [comment] 2015-12-08 19:57
> This only works when set as attributes in the CLI and not when defined in the document attributes section. 

It should work either way.

**Closed** 2020-07-11 16:48 UTC
Labels: question
