### ISSUE TITLE
Attributes from pom.xml not substituted in PDF (sometimes)

### ISSUE THREAD

**Issue by LaurianeDPX** [asciidoctor/asciidoctor-maven-plugin#278] opened 2016-11-29 15:00 UTC
I use Asciidoc Maven plugin to generate a PDF. I have this at the beginning of the document:

```
= {document-title} 
{organization}
v{project-version}, {localdate}
:numbered:
:toc: macro
```

`document-title`, `organization` and `project-version` come from my pom.xml:

```
<configuration>
    <attributes>
        <document-title>${project.name}</document-title>
        <project-version>${project.version}</project-version>
        <organization>${project.organization.name}</organization>
    </attributes>
</configuration>
```

My problem is that `project-version` is not substituted by its value, it is just blank.

The interesting thing is when I use this:

```
v{project-version}, 2016-11-29
```
or this:
```
v{project-version}
```
`project-version` is substituted !

Any idea how to solve this ? Thanks !

Additional information:
- `asciidoctor-maven-plugin` version 1.5.3
- `asciidoctorj-pdf` version 1.5.0-alpha-11
- `jruby-complete` version 9.0.5.0
- `asciidoctorj` version 1.5.4

And the doc type is `book`.

**Comment by abelsromero** [comment] 2016-11-29 17:46
I reproduced the issue using directly ascidoctor 1.5.5 (ruby) in the shell. /cc @mojavelinux 
```
asciidoctor -b html5 -a document-title="AsciiDoc to HTML Maven Example" -a project-version="1.0.0-SNAPSHOT" -a organization="my super org" demo.adoc
```
`project-version` get replaced in text, but not in the header.

In my case however, I can only show the version in the header when it's alone. No other option works.
Also, if instead of `project-version` I use `version-label` it work,s but I don't think it is legal to replace that internal attribute.

**Comment by mojavelinux** [comment] 2016-11-29 22:19
It may be that substitutions aren't performed in revision line (I'd need to check). But it shouldn't matter since there is a far simpler way to do this. Just leave off the revision line and set these attributes:

```
<configuration>
    <attributes>
        <document-title>${project.name}</document-title>
        <revnumber>${project.version}</revnumber>
        <revdate>${maven.build.date}</revdate>
        <organization>${project.organization.name}</organization>
    </attributes>
</configuration>
```

**Comment by LaurianeDPX** [comment] 2016-11-30 09:32
Your solution works like a charm @mojavelinux and thanks for your very quick answers.
I had to use `${maven.build.timestamp}` instead of `${maven.build.date}` though.

Thank you !

**Comment by mojavelinux** [comment] 2016-11-30 10:08
:+1:

**Comment by abelsromero** [comment] 2016-11-30 12:47
I was going to add this in the README's tips section but I noticed that the documentation (http://asciidoctor.org/docs/user-manual/#builtin-attributes) uses the attribute `title` instead of `document-title`.
Which should be the recommended?

**Comment by mojavelinux** [comment] 2016-11-30 21:48
To be honest, I wouldn't recommend using either. Instead, the attribute should describe what it holds. In this case, it's `project-name`.

```
<project-name>${project.name}</project-name>
```

Then you'd write:

```
= {project-name}
```

You could also set doctitle, but I think this is actually clearer.

**Comment by abelsromero** [comment] 2016-12-01 06:52
I make sense, thanks a lot.

**Comment by abelsromero** [comment] 2020-10-12 12:42
Closing because documentation is available and the original issue does not reproduce with:

* asciidoctor-maven-plugin version: 2.1.0
* asciidoctorj-pdf version: 1.5.3
* jruby-complete version: 9.2.13.0
* asciidoctorj version: 2.4.1

**Closed by abelsromero** 2020-10-12 12:42 UTC
