### ISSUE TITLE
Error on OpenJ9 JVM: "unknown encoding name - UTF8"

### ISSUE THREAD

**Issue by enikao** [asciidoctor/asciidoctor-maven-plugin#412] opened 2019-07-17 12:52 UTC
If I run my build script with Hotspot JVM, it works fine. However, using Eclipse OpenJ9 fails.

I tried with both asciidoctor-maven-plugin v1.6.0 and v2.0.0-RC.1.

Working JDK:
jdk-8.0.212.04-hotspot (https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u212-b04/OpenJDK8U-jdk_x64_windows_hotspot_8u212b04.msi)

Non-Working JDK:
jdk-8.0.212.04-openj9 (https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u212-b04_openj9-0.14.2/OpenJDK8U-jdk_x64_windows_openj9_8u212b04_openj9-0.14.2.msi)

Exception:
````
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.6.0:process-asciidoc (output-html) on project xxx: Execution output-html of goal org.asciidoctor:asciidoctor-maven-plugin:1.6.0:process-asciidoc failed: unknown encoding name - UTF8 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.6.0:process-asciidoc (output-html) on project xxx: Execution output-html of goal org.asciidoctor:asciidoctor-maven-plugin:1.6.0:process-asciidoc failed: unknown encoding name - UTF8
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution output-html of goal org.asciidoctor:asciidoctor-maven-plugin:1.6.0:process-asciidoc failed: unknown encoding name - UTF8
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: org.jruby.exceptions.MainExitException: unknown encoding name - UTF8
````

**Comment by abelsromero** [comment] 2019-07-17 14:37
I assume Windows?
Also, can you confirm all files in the project are encoded in UTF-8?

**Comment by abelsromero** [comment] 2019-07-17 20:59
I could reproduce it with any JDK injecting a wrong encoding with `export MAVEN_OPTS="-Dfile.encoding=UTF8"`. JRuby is picking this up and it fails because this is a wrong encoding name.
Could you check if a wrong `file.encoding` environment variable is leaking somehow?

Btw, note that setting it in `<project.build.sourceEncoding>` does not trigger the issue, since this value is not passed to JRuby.

**Comment by enikao** [comment] 2019-07-18 08:25
Yes, Windows platform.

I guess it's not related to file encoding. I tried to manipulate all of the following settings, without effect on the error message:
* Maven `project.build.sourceEncoding`
* Maven `project.reporting.outputEncoding`
* asciidoctor-maven-plugin configuration `encoding`

The only thing I changed between running with Hotspot or OpenJ9 was JAVA_HOME.

OTOH, once I forced maven to `-Dfile.encoding=UTF-8`, also the OpenJ9 variant succeeded.

If we look up the reference at https://docs.oracle.com/javase/8/docs/technotes/guides/intl/encoding.doc.html, both variants `UTF-8` and `UTF8` _should_ be ok.

**Comment by enikao** [comment] 2019-07-19 13:43
Thanks for all the effort!

````
Microsoft Windows [Version 10.0.15063]

nstotz@L-NL-20053 C:\Users\nstotz
$ cd git

nstotz@L-NL-20053 C:\Users\nstotz\git
$ cd asciidoctor-maven-examples

nstotz@L-NL-20053 C:\Users\nstotz\git\asciidoctor-maven-examples
$ cd asciidoc-to-html-example

nstotz@L-NL-20053 C:\Users\nstotz\git\asciidoctor-maven-examples\asciidoc-to-html-example
$ set
ALLUSERSPROFILE=C:\ProgramData
ANSICON=232x1000 (232x59)
ANSICON_DEF=7
APPDATA=C:\Users\nstotz\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=L-NL-20053
ComSpec=C:\windows\system32\cmd.exe
ConEmuANSI=ON
ConEmuAnsiLog=
ConEmuArgs=
ConEmuArgs2=
ConEmuBackHWND=0x00160BE8
ConEmuBaseDir=C:\Program Files\ConEmu\ConEmu
ConEmuBaseDirShort=C:\PROGRA~1\ConEmu\ConEmu
ConEmuBuild=190108
ConEmuCfgDir=C:\Users\nstotz\AppData\Roaming
ConEmuConfig=
ConEmuDir=C:\Program Files\ConEmu
ConEmuDrawHWND=0x00210F7C
ConEmuDrive=C:
ConEmuHooks=Enabled
ConEmuHWND=0x00040ED6
ConEmuPalette=<xterm>
ConEmuPID=2392
ConEmuServerPID=6612
ConEmuTask={Shells::cmd}
ConEmuWorkDir=C:\Users\nstotz
ConEmuWorkDrive=C:
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
GTK_BASEPATH=C:\Program Files (x86)\GtkSharp\2.12\
HOME=C:\Users\nstotz
HOMEDRIVE=Z:
HOMEPATH=\
HOMESHARE=\\{REDACTED}\nl\HomeDrive\nstotz
JAVA_HOME=C:\Program Files\AdoptOpenJDK\jdk-8.0.212.04-hotspot
LOCALAPPDATA=C:\Users\nstotz\AppData\Local
LOGONSERVER=\\{REDACTED}
NUMBER_OF_PROCESSORS=4
OS=Windows_NT
Path=C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program Files\ConEmu;C:\Program Files\ConEmu\ConEmu;C:\Program Files\AdoptOpenJDK\jdk-8.0.212.04-hotspot\bin;C:\Program Files\AdoptOpenJDK\jdk-8.0.212.04-openj9\bin;C:\Program Files\AdoptOpenJDK\jdk-12.0.1.12-openj9\bin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Maven\bin;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Users\nstotz\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Ant\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=5e03
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$E[m$E[32m$E]9;8;"USERNAME"$E\@$E]9;8;"COMPUTERNAME"$E\$S$E[92m$P$E[90m$_$E[90m$$$E[m$S$E]9;12$E\
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files\Intel\Wired Networking\
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\windows
TEMP=C:\Users\nstotz\AppData\Local\Temp
TMP=C:\Users\nstotz\AppData\Local\Temp
UATDATA=C:\windows\CCM\UATData\{REDACTED}
USERDNSDOMAIN={REDACTED}
USERDOMAIN={REDACTED}
USERDOMAIN_ROAMINGPROFILE={REDACTED}
USERNAME=nstotz
USERPROFILE=C:\Users\nstotz
windir=C:\windows

nstotz@L-NL-20053 C:\Users\nstotz\git\asciidoctor-maven-examples\asciidoc-to-html-example
$ mvn
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building AsciiDoc to HTML Maven Example 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- asciidoctor-maven-plugin:2.0.0-RC.1:process-asciidoc (asciidoc-to-html) @ asciidoc-to-html-example ---
Downloading: https://repo.maven.apache.org/maven2/org/jruby/jruby-complete/9.2.7.0/jruby-complete-9.2.7.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/jruby/jruby-complete/9.2.7.0/jruby-complete-9.2.7.0.pom (13 kB at 22 kB/s)
Downloading: https://repo.maven.apache.org/maven2/org/asciidoctor/asciidoctorj/2.0.0/asciidoctorj-2.0.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/asciidoctor/asciidoctorj/2.0.0/asciidoctorj-2.0.0.pom (2.6 kB at 31 kB/s)
Downloading: https://repo.maven.apache.org/maven2/org/asciidoctor/asciidoctorj-api/2.0.0/asciidoctorj-api-2.0.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/asciidoctor/asciidoctorj-api/2.0.0/asciidoctorj-api-2.0.0.pom (1.9 kB at 29 kB/s)
Downloading: https://repo.maven.apache.org/maven2/org/jruby/jruby-complete/9.2.7.0/jruby-complete-9.2.7.0.jar
Downloading: https://repo.maven.apache.org/maven2/org/asciidoctor/asciidoctorj/2.0.0/asciidoctorj-2.0.0.jar
Downloading: https://repo.maven.apache.org/maven2/org/asciidoctor/asciidoctorj-api/2.0.0/asciidoctorj-api-2.0.0.jar
Downloaded: https://repo.maven.apache.org/maven2/org/asciidoctor/asciidoctorj-api/2.0.0/asciidoctorj-api-2.0.0.jar (53 kB at 253 kB/s)
Downloaded: https://repo.maven.apache.org/maven2/org/asciidoctor/asciidoctorj/2.0.0/asciidoctorj-2.0.0.jar (1.6 MB at 1.8 MB/s)
Downloaded: https://repo.maven.apache.org/maven2/org/jruby/jruby-complete/9.2.7.0/jruby-complete-9.2.7.0.jar (27 MB at 2.2 MB/s)
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Rendered C:\Users\nstotz\git\asciidoctor-maven-examples\asciidoc-to-html-example\src\docs\asciidoc\example-manual.adoc
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ asciidoc-to-html-example ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\nstotz\git\asciidoctor-maven-examples\asciidoc-to-html-example\src\main\resources
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 23.316 s
[INFO] Finished at: 2019-07-19T15:37:18+02:00
[INFO] Final Memory: 40M/285M
[INFO] ------------------------------------------------------------------------

nstotz@L-NL-20053 C:\Users\nstotz\git\asciidoctor-maven-examples\asciidoc-to-html-example
$ set JAVA_HOME=c:\Program Files\AdoptOpenJDK\jdk-8.0.212.04-openj9

nstotz@L-NL-20053 C:\Users\nstotz\git\asciidoctor-maven-examples\asciidoc-to-html-example
$ set
ALLUSERSPROFILE=C:\ProgramData
ANSICON=232x1000 (232x59)
ANSICON_DEF=7
APPDATA=C:\Users\nstotz\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=L-NL-20053
ComSpec=C:\windows\system32\cmd.exe
ConEmuANSI=ON
ConEmuAnsiLog=
ConEmuArgs=
ConEmuArgs2=
ConEmuBackHWND=0x00160BE8
ConEmuBaseDir=C:\Program Files\ConEmu\ConEmu
ConEmuBaseDirShort=C:\PROGRA~1\ConEmu\ConEmu
ConEmuBuild=190108
ConEmuCfgDir=C:\Users\nstotz\AppData\Roaming
ConEmuConfig=
ConEmuDir=C:\Program Files\ConEmu
ConEmuDrawHWND=0x00210F7C
ConEmuDrive=C:
ConEmuHooks=Enabled
ConEmuHWND=0x00040ED6
ConEmuPalette=<xterm>
ConEmuPID=2392
ConEmuServerPID=6612
ConEmuTask={Shells::cmd}
ConEmuWorkDir=C:\Users\nstotz
ConEmuWorkDrive=C:
ERROR_CODE=0
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
GTK_BASEPATH=C:\Program Files (x86)\GtkSharp\2.12\
HOME=C:\Users\nstotz
HOMEDRIVE=Z:
HOMEPATH=\
HOMESHARE=\\{REDACTED}\nl\HomeDrive\nstotz
JAVA_HOME=c:\Program Files\AdoptOpenJDK\jdk-8.0.212.04-openj9
LOCALAPPDATA=C:\Users\nstotz\AppData\Local
LOGONSERVER=\\{REDACTED}
NUMBER_OF_PROCESSORS=4
OS=Windows_NT
Path=C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program Files\ConEmu;C:\Program Files\ConEmu\ConEmu;C:\Program Files\AdoptOpenJDK\jdk-8.0.212.04-hotspot\bin;C:\Program Files\AdoptOpenJDK\jdk-8.0.212.04-openj9\bin;C:\Program Files\AdoptOpenJDK\jdk-12.0.1.12-openj9\bin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Maven\bin;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Users\nstotz\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Ant\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=5e03
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$E[m$E[32m$E]9;8;"USERNAME"$E\@$E]9;8;"COMPUTERNAME"$E\$S$E[92m$P$E[90m$_$E[90m$$$E[m$S$E]9;12$E\
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files\Intel\Wired Networking\
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\windows
TEMP=C:\Users\nstotz\AppData\Local\Temp
TMP=C:\Users\nstotz\AppData\Local\Temp
UATDATA=C:\windows\CCM\UATData\{REDACTED}
USERDNSDOMAIN={REDACTED}
USERDOMAIN={REDACTED}
USERDOMAIN_ROAMINGPROFILE={REDACTED}
USERNAME=nstotz
USERPROFILE=C:\Users\nstotz
windir=C:\windows

nstotz@L-NL-20053 C:\Users\nstotz\git\asciidoctor-maven-examples\asciidoc-to-html-example
$ mvn
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building AsciiDoc to HTML Maven Example 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- asciidoctor-maven-plugin:2.0.0-RC.1:process-asciidoc (asciidoc-to-html) @ asciidoc-to-html-example ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.541 s
[INFO] Finished at: 2019-07-19T15:38:11+02:00
[INFO] Final Memory: 8M/13M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:2.0.0-RC.1:process-asciidoc (asciidoc-to-html) on project asciidoc-to-html-example: Execution asciidoc-to-html of goal org.asciidoctor:asciidoctor-maven-plugin:2.0.0-RC.1:process-asciidoc failed: unknown encoding name - UTF8 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

nstotz@L-NL-20053 C:\Users\nstotz\git\asciidoctor-maven-examples\asciidoc-to-html-example
$
````

**Comment by abelsromero** [comment] 2019-07-20 08:24
I was hoping to see something there, but no luck. Sorry to ask you to run stuff, but I haven't been able to reproduce it.
- Does this fail from a normal cmd command?
- Can you check there's no jruby configuration in your machine? https://github.com/jruby/jruby/wiki/ConfiguringJRuby
- Can you run with `-e` flag? if the stack trace 100% confirm this is in jruby, I'll ask help from them to see if there's more debugging to be done

**Comment by abelsromero** [comment] 2019-07-20 09:31
Further checking I see it does not happen in MacOS or Linux.

**Comment by enikao** [comment] 2019-07-22 09:03
Yes, it's the same from normal cmd.
No, I don't have any JRuby config.

**Comment by abelsromero** [comment] 2019-07-23 07:12
I am out of ideas, I asked https://github.com/jruby/jruby/issues/4546 with the summary of our findings to see if the jRuby team can help see the cause.

**Comment by abelsromero** [comment] 2020-07-05 14:25
Closing: reporter confirmed fix in upstream https://github.com/jruby/jruby/issues/4546#issuecomment-514667310

**Closed by abelsromero** 2020-07-05 14:25 UTC
Labels: tracking
